spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:h2:mem:spring
    username: user
    password: pw
  h2:
    console:
      enabled: true
logging:
  level:
    tacos: DEBUG
taco:
  orders:
    pageSize: 25